routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/article/{slug?}', 'BlogController@article')->name('article');

Route::group(['prefix'=>'admin', 'namespace'=>'Admin', 'middleware'=>['auth']], function(){
  Route::get('/', 'DashboardController@dashboard')->name('admin.index');
  Route::resource('/category', 'CategoryController', ['as'=>'admin']);
  Route::resource('/article', 'ArticleController', ['as'=>'admin']);
  Route::group(['prefix' => 'user_managment', 'namespace' => 'UserManagment'], function() {
  	Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
  });
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Article.php
<?php

namespace App;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Support\Str;

class Article extends Model
{
    // Mass assigned
    protected $fillable = ['title', 'slug', 'description_short', 'description', 'meta_title', 'meta_description', 'meta_keyword', 'published', 'created_by', 'modified_by'];

    // Mutators
    public function setSlugAttribute($value) {
      $this->attributes['slug'] = Str::slug( mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    public function categories()
    {
      return $this->morphToMany('App\Category', 'categoryable');
    }
	
    public function images()
    {
      return $this->hasOne('App\Image','article_id','id');
    }
	
    public function scopeLastArticles($query, $count)
    {
      return $query->orderBy('created_at', 'desc')->take($count)->get();
    }
	public function getArticleImages($article_id)
    {
      return DB::table('images')->where('article_id', $article_id)->get(['imgsrc','miniature','title'])->first();
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use App\Image;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
          'articles' => Article::orderBy('created_at', 'desc')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.create', [
          'article'    => [],
          'categories' => Category::with('children')->where('parent_id', 0)->get(),
          'delimiter'  => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = Article::create($request->all());

        if($request->input('categories')) :
           $article->categories()->attach($request->input('categories'));
        endif;
			
		if($request->file('images')):
		    $imageName = time() . '.' . $request->file('images')->getClientOriginalExtension();
            $request->file('images')->move(public_path('images'), $imageName);
			$miniature = $this->resize($imageName, 300, 200);
			
		    $article->images()->create([
		       'imgsrc' => '/images/'.$imageName, 
			   'title' => $request->input('image_title'), 
			   'miniature' => $miniature
			]);
		endif;

        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', [
          'article'    => $article,
          'categories' => Category::with('children')->where('parent_id', 0)->get(),
		  'image'      => Image::where('article_id', $article->id)->get(['imgsrc','miniature','title'])->first(),
          'delimiter'  => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->update($request->except('slug'));

        $article->categories()->detach();
        if($request->input('categories')) :
          $article->categories()->attach($request->input('categories'));
        endif;
			
		if($request->file('images') && !$request->input('deleteimg')):
		   $article->images()->delete();
		   $imageName = time() . '.' . $request->file('images')->getClientOriginalExtension();
           $request->file('images')->move(public_path('images'), $imageName);
		   $miniature = $this->resize($imageName, 300, 200);
		   
		   $article->images()->create(['imgsrc' => '/images/'.$imageName, 'miniature' => $miniature]);
		endif;
		
		if($request->input('image_title') && !$request->input('deleteimg')):
		   $article->images()->update(['title' => $request->input('image_title')]);
		endif;
		
		if($request->input('deleteimg')):
		   $article->images()->delete();
		endif;

        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->categories()->detach();
		$article->images()->delete();
        $article->delete();

        return redirect()->route('admin.article.index');
    }
	
    public function resize($image, $w_o = 300, $h_o = 200) { 
	
	    $savepath = '/images/miniature/'.$w_o.'_'.$h_o.'_'.$image;	
	    
		$image = $_SERVER['DOCUMENT_ROOT'].'/images/'.$image;	
	
        list($w_i, $h_i, $type) = getimagesize($image); 
	
        $types = array("", "gif", "jpeg", "png"); 
	
        $ext = $types[$type]; 
	
        if($ext) { 
          $func = 'imagecreatefrom'.$ext; // Получаем название функции, соответствующую типу, для создания изображения 
          $img_i = $func($image); 
        } 
	
        if (!$h_o) $h_o = $w_o / ($w_i / $h_i); 
        if (!$w_o) $w_o = $h_o / ($h_i / $w_i); 
	
        $img_o = imagecreatetruecolor($w_o, $h_o); 
        imagecopyresampled($img_o, $img_i, 0, 0, 0, 0, $w_o, $h_o, $w_i, $h_i); 
		/* Переносим изображение из исходного в выходное, масштабируя его */
        $func = 'image'.$ext; // Получаем название функции, для сохранения результата 
	
        $func($img_o, $_SERVER['DOCUMENT_ROOT'].$savepath); 
		
		return $savepath;
  }
  
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

<div class="container">

  @component('admin.components.breadcrumb')
    @slot('title') Создание записи @endslot
    @slot('parent') Главная @endslot
    @slot('active') Записи @endslot
  @endcomponent

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#default_panel">Основные поля</a></li>
	<li><a data-toggle="tab" href="#desc_panel">Описание</a></li>
    <li><a data-toggle="tab" href="#seo_panel">SEO поля</a></li>
  </ul>

  <form class="form-horizontal" action="{{route('admin.article.store')}}" method="post" enctype="multipart/form-data">
    {{ csrf_field() }}

    {{-- Form include --}}
    @include('admin.articles.partials.form')

    <input type="hidden" name="created_by" value="{{Auth::id()}}">
  </form>
</div>

@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

<div class="container">

  @component('admin.components.breadcrumb')
    @slot('title') Редактирование записи @endslot
    @slot('parent') Главная @endslot
    @slot('active') Записи @endslot
  @endcomponent

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#default_panel">Основные поля</a></li>
	<li><a data-toggle="tab" href="#desc_panel">Описание</a></li>
    <li><a data-toggle="tab" href="#seo_panel">SEO поля</a></li>
  </ul>

  <form class="form-horizontal" action="{{route('admin.article.update', $article)}}" method="post" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="put">
    {{ csrf_field() }}

    {{-- Form include --}}
    @include('admin.articles.partials.form')

    <input type="hidden" name="modified_by" value="{{Auth::id()}}">
  </form>
</div>

@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

<div class="container">

  @component('admin.components.breadcrumb')
    @slot('title') Список записей @endslot
    @slot('parent') Главная @endslot
    @slot('active') Записи @endslot
  @endcomponent

  <hr>

  <a href="{{route('admin.article.create')}}" class="btn btn-success pull-right"><i class="fa fa-plus-square-o"></i> Создать запись</a>
  <table class="table table-striped">
    <thead>
      <th>Наименование</th>
      <th>Активность</th>
      <th class="text-right">Действие</th>
    </thead>
    <tbody>
      @forelse ($articles as $article)
        <tr>
          <td>{{$article->title}}</td>
          <td>{{$article->published}}</td>
          <td class="text-right">
            <form onsubmit="if(confirm('Удалить?')){ return true }else{ return false }" action="{{route('admin.article.destroy', $article)}}" method="post">
              <input type="hidden" name="_method" value="DELETE">
              {{ csrf_field() }}
 
              <a class="btn btn-default" href="{{route('article', $article->slug)}}" target="_blank" title="Просмотреть"><i class="fa fa-eye" aria-hidden="true"></i></a>
              <a class="btn btn-primary" href="{{route('admin.article.edit', $article)}}" title="Редактировать"><i class="fa fa-edit"></i></a>
              <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"><h2>Данные отсутствуют</h2></td>
        </tr>
      @endforelse
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">
          <ul class="pagination pull-right">
            {{$articles->links()}}
          </ul>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

@endsection